server:
  port: "9000"

database:
  dsn: "postgresql://aiba_ou74_user:362sE3ZwMZClKL8SHOHTn8lS2VB6a003@dpg-d4kn4d49c44c73f2ihsg-a/aiba_ou74"

ai:
  provider: "gemini"

confluence:
  base_url: ""
  user: ""
  token: ""

# Optional defaults (можно переопределить через env)
jwt_secret: "a-string-secret-at-least-256-bits-long"
google_client_id: ""
auth_token: ""
basic_user: ""
basic_pass: ""
